ACH/urls.py
from django.urls import path

from ACH import views

app_name = 'ACH'

urlpatterns = [
    path('', views.show_index_html, name='index'),
    path('ai_info/', views.show_ai_info_html, name='ai_info'),
    path('board/', views.BoardListView.as_view(), name='board_list'),
    path('create/', views.BoardCreateView.as_view(), name='board_create')
]

clubwebsite/urls.py
from django.contrib import admin
from django.urls import path, include

import ACH.views

urlpatterns = [
    path('ACH/', include('ACH.urls')),
    path('admin/', admin.site.urls),
]

ACH/models.py
from django.db import models
from django.shortcuts import resolve_url

class Board(models.Model):
    title = models.CharField(max_length=100)  # 게시글의 제목
    content = models.TextField()  # 게시글의 내용
    image = models.ImageField(upload_to='posts/%Y/%m/%d/', null=True, blank=True)  # 게시글의 이미지
    created_at = models.DateTimeField(auto_now_add=True)  # 작성 시간
    updated_at = models.DateTimeField(auto_now=True)  # 수정 시간

    def __str__(self):  # 객체를 문자열로 표현할 때 사용
        return f'제목: {self.title}, 작성날짜: {self.created_at}, 수정날짜: {self.updated_at}'
    def get_absolute_url(self):  # 이 객체의 상세 페이지 URL을 반환
        return resolve_url('post:detail', pk=self.id)

class CreativeAI(models.Model):
    name = models.CharField(max_length=100)  # 생성형 AI의 이름
    description = models.TextField()  # 생성형 AI에 대한 설명
    image = models.ImageField(upload_to='ai_images/%Y/%m/%d/', null=True, blank=True)  # 생성형 AI와 관련된 이미지
    rule = models.TextField()  # 생성형 AI의 규칙
    link = models.URLField(max_length=200)  # 생성형 AI에 대한 링크

    def __str__(self):  # 객체를 문자열로 표현할 때 사용
        return f'이름: {self.name}'

    def get_absolute_url(self):  # 이 객체의 상세 페이지 URL을 반환
        return resolve_url('ai:detail', pk=self.id)

ACH/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from ACH.models import Board, CreativeAI


def show_index_html(request):
    return render(request, 'ACH/index.html')

def show_ai_info_html(request):
    ai_list = CreativeAI.objects.all()  # CreativeAI 모델의 모든 객체를 가져옴
    return render(request, 'ACH/ai_info.html', {'ai_list': ai_list})

class BoardListView(ListView):
    model = Board

class BoardCreateView(CreateView):
    model = Board
    fields = '__all__'
    template_name_suffix = '_create'
    success_url = reverse_lazy('ACH:board_list')

ACH/templates/ACH/ai_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ACH/templates/ACH/ai_info.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/ai_info.css' %}"/>
    <title>AI 정보</title>
</head>
<body>
    <!--상단 내비 바-->
    <nav>
        <a href="{% url "ACH:index" %}"><p>< HOME</p></a>
        <ul>
            <li><a href="#description">생성형AI란?</a></li>
            <li><a href="#ai-content">AI정보</a></li>
        </ul>
    </nav>

    <section id="description">
        <div class="preface">
            <div class="description">
                <h1>당신이 알고있는 생성형AI는 몇가지인가요?</h1>
                <p><strong style="font-size: 20px">생성형 AI란,</strong><br>생성형 인공지능 또는 생성형 AI는 프롬프트에 대응하여 텍스트, 이미지, 기타 미디어를 생성할 수 있는 인공지능 시스템입니다.<br>
                chatGPT와 같이 접근성과 범용성이 좋은 AI를 체험해 보신적이 있으신가요?<br>
                채팅형 AI 뿐만 아니라, 위 설명처럼 이미지, 음성, 소설, 코딩 등 다양한 분야에서 생성형 AI는 발전하고 있습니다.<br>
                보다 다양하고 넓은 생성형 AI에 빠져보아요!
                </p>
            </div>
            <img src="{% static "img/인공지능.png" %}">
        </div>
    </section>

    <!--AI 정보-->
    <div class="info-container" id="ai-content">
        <div class="info-title">
            <h1>원하는 생성형 AI를 클릭해주세요! 👆️</h1>
            <p><strong>"커서"</strong>를 올리면 AI의 이름과 특징을,<br><strong>"클릭"</strong>하면 더 자세한 특징과 사용방법에 대해 조회할 수 있습니다.</p>
        </div>
        <div class="info-content">
            <div class="ai-container"><!--미드저니-->
                <img src="{% static "img/미드저니.png" %}">
                <div class="text">
                    <h3>미드저니,</h3>
                    <p>프롬프트를 활용한 이미지 생성 AI</p>
                </div>
            </div>
            <div class="ai-container"><!--챗지피티-->
                <img src="{% static "img/챗지피티.png" %}">
                <div class="text">
                    <h3>ChatGPT,</h3>
                    <p>채팅형 프롬프트를 활용한 다양한 텍스트 결과 생성</p>
                </div>
            </div>
            <div class="ai-container"><!--레오나르도-->
                <img src="{% static "img/레오나르도.png" %}">
                <div class="text">
                    <h3>레오나르도,</h3>
                    <p>프롬프트를 활용한 이미지 생성 및<br>사용자의 그림을 실시간 인식하여<br>인공지능 방식으로 출력하는 이미지 생성 AI</p>
                </div>
            </div>
            <div class="ai-container"><!--코파일럿-->
                <img src="{% static "img/코파일럿.png" %}">
                <div class="text">
                    <h3>Github Copliot,</h3>
                    <p>코드를 인식하여 자동완성 해주는 코드형 AI</p>
                </div>
            </div>
        </div>
    </div>

    <!--푸터-->
    <footer>
        <p class="logo">ACH</p>
        <ul>
            <a href="https://github.com/de-quei/" target="_blank"><li>Github</li></a>
            <a href="https://instagram.com/de_quei/" target="_blank"><li>Instagram</li></a>
            <a href="https://velog.io/@de-quei/posts" target="_blank"><li>Velog</li></a>
        </ul>
        <p class="copyright">© 2024 김현지. All rights reserved</p>
    </footer>
</body>
</html>

ACH/templates/ACH/board.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/board.css' %}">
    <title>Title</title>
</head>
<body>

</body>
</html>

ACH/templates/ACH/board_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>board_create</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="+ post">
    </form>
</body>
</html>

ACH/templates/ACH/board_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/board.css' %}">
    <title>Board List</title>
    <style>
        .container {
            width: 80%;
            margin: 0 auto;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .card {
            width: 100%;
            border: 1px solid #ccc;
            border-radius: 8px;
            padding: 16px;
            margin: 16px 0;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            display: flex;
            flex-direction: column;
        }
        .card-title {
            font-size: 1.3em;
            margin-bottom: 8px;
        }
        .card-content {
            font-size: 1em;
            margin-bottom: 5px;
        }
        .card-dates {
            display: flex;
            justify-content: space-between;
            font-size: 0.9em;
            color: #555;
        }
        .create-button {
            display: inline-block;
            padding: 10px 20px;
            margin-top: 20px;
            background-color: #000;
            color: white;
            text-decoration: none;
            border-radius: 5px;
        }
        .create-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>게시판</h1>
        {% for board in board_list %}
            <div class="card">
                <div class="card-title">{{ board.title }}</div>
                <div class="card-content">{{ board.content }}</div>
                <img src="{{ board.image }}" alt="사진" style="margin-bottom: 5px">
                <div class="card-dates">
                    <div>작성시간: {{ board.created_at }}</div>
                </div>
            </div>
        {% endfor %}
        <a class="create-button" href="{% url 'ACH:board_create' %}">+ Create New</a>
    </div>
</body>
</html>

ACH/templates/ACH/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <title>ACH</title>
</head>
<body>
    <!--상단 내비바-->
    <nav>
        <p>ACH</p>
        <ul>
            <li><a href="#introduce">소개말</a></li>
            <li><a href="#ai-info">AI정보</a></li>
            <li><a href="#board">게시판</a></li>
        </ul>
    </nav>

    <!--첫 번째 섹션. 소개말-->
    <section id="introduce">
        <div class="introduce">
            <div class="preface">
                <h1>ACH란?</h1>
                <p>ACH란, <strong>AI Creations Hub</strong>의 약자로써,<br>생성형 인공지능의 대한 정보와 사용 방법을 제공하고<br>더 좋은 결과물을 낼 수 있도록 공유할 수 있는 커뮤니티형 정보제공 서비스입니다.</p>
            </div>
            <img src="{% static 'img/ai_vector.png' %}">
        </div>
    </section>

    <!--두 번째 섹션, 인공지능 정보-->
    <section id="ai-info">
        <div class="ai-info">
            <div class="info-title">
                <h1>다양한 생성형AI를<br>ACH에서 만나보세요! 👋</h1>
                <a href="{% url "ACH:ai_info" %}">👉 더 많은 생성형 AI 종류를 알고싶다면?</a> <!--ai정보.html url을 첨부할 것-->
            </div>
            <div class="auto-slider">
                <div class="img-box">
                    <div><img src="{% static 'img/미드저니.png' %}"></div>
                    <div><img src="{% static 'img/챗지피티.png' %}"></div>
                    <div><img src="{% static 'img/레오나르도.png' %}"></div>
                    <div><img src="{% static 'img/코파일럿.png' %}"></div>
                    <div><img src="{% static 'img/미드저니.png' %}"></div>
                    <div><img src="{% static 'img/챗지피티.png' %}"></div>
                    <div><img src="{% static 'img/레오나르도.png' %}"></div>
                    <div><img src="{% static 'img/코파일럿.png' %}"></div>
                </div>
            </div>
        </div>
    </section>

    <!--세 번째 섹션, 게시판 기능 소개-->
    <section id="board">
        <div class="board">
            <img src="{% static 'img/폰.png' %}">
            <div class="description">
                <h1>게시판에서 모두와 함께 공유해보세요!</h1>
                <p>생성형 인공지능은 사용자가 프롬프트를 어떻게 활용하냐에 따라<br>결과물의 매끄러움이 좌우됩니다.<br>서로의 작업물을 감상하여 영감을 얻고 생성형 AI를 더 효율적이게 사용해보거나,<br>나의 작업물도 자랑해보아요!</p>
                <a href="{% url "ACH:board_list" %}">👉 게시판 바로가기</a> <!--게시판.html url을 첨부할 것-->
            </div>
        </div>
    </section>

    <!--푸터-->
    <footer>
        <p class="logo">ACH</p>
        <ul>
            <a href="https://github.com/de-quei/" target="_blank"><li>Github</li></a>
            <a href="https://instagram.com/de_quei/" target="_blank"><li>Instagram</li></a>
            <a href="https://velog.io/@de-quei/posts" target="_blank"><li>Velog</li></a>
        </ul>
        <p class="copyright">© 2024 김현지. All rights reserved</p>
    </footer>
</body>
</html>